# Simple 3 time steps RNN without using any of TensorFlow's RNN operations

(Based on Hands-On Machine Learning of Auriél Géron)

In [43]:
import numpy as np
import tensorflow as tf

# Size of the input vector at each time step
n_inputs = 3
# Number of recurrent neurons
n_neurons = 5

# Input vectors, one vector for each time step
X0 = tf.placeholder(tf.float32, [None, n_inputs])
X1 = tf.placeholder(tf.float32, [None, n_inputs])
X2 = tf.placeholder(tf.float32, [None, n_inputs])

# Weight matrices
Wx = tf.Variable(tf.random_normal(shape=[n_inputs, n_neurons], dtype=tf.float32, seed=42))
Wy = tf.Variable(tf.random_normal(shape=[n_neurons, n_neurons], dtype=tf.float32, seed=42))
# Bias
b = tf.Variable(tf.zeros([1, n_neurons], dtype=tf.float32))

# Output of the recurrent neurons
Y0 = tf.tanh(tf.matmul(X0, Wx) + b) # t=0
Y1 = tf.tanh(tf.matmul(X1, Wx) + tf.matmul(Y0, Wy) + b) # t=1
Y2 = tf.tanh(tf.matmul(X2, Wx) + tf.matmul(Y1, Wy) + b) # t=2

init = tf.global_variables_initializer()

# Mini-batch t=0
X0_batch = np.array([[0, 1, 2], 
                     [3, 4, 5], 
                     [6, 7, 8], 
                     [9, 0, 1]])
# Mini-batch t=1
X1_batch = np.array([[9, 8, 7], 
                     [0, 0, 0], 
                     [6, 5, 4], 
                     [3, 2, 1]]) 
# Mini-batch t=2
X2_batch = np.array([[1, 1, 1], 
                     [2, 2, 2], 
                     [3, 3, 3], 
                     [4, 4, 4]])

with tf.Session() as sess:
    init.run()
    feed_dict = {X0: X0_batch, X1: X1_batch, X2: X2_batch}
    Y0_val, Y1_val, Y2_val = sess.run([Y0, Y1, Y2], feed_dict=feed_dict)
    
    print('output at time step 0 \n', Y0_val)
    print('output at time step 1 \n', Y1_val)
    print('output at time step 2 \n', Y2_val)

output at time step 0 
 [[-0.95407802 -0.99674022  0.98660398  0.57785892 -0.98755085]
 [-0.30700076 -0.99999917  0.99999976  0.63324869 -0.99999374]
 [ 0.8457135  -1.          1.          0.68283153 -1.        ]
 [ 1.         -0.99766296  1.         -0.99999917 -0.98221558]]
output at time step 1 
 [[ 0.99872833 -1.          1.         -0.99214447 -1.        ]
 [-0.96752214 -0.9684667   0.99960893 -0.99444956 -0.89819932]
 [ 0.99972194 -0.99999893  1.         -0.99968082 -0.99999726]
 [ 0.99847519 -0.99978107  0.99999833 -0.99886143 -0.11810157]]
output at time step 2 
 [[ 0.58409685 -0.99991119  0.99998206 -0.99647796 -0.11304511]
 [-0.88040298 -0.99998939  0.99997598 -0.87694168 -0.8552171 ]
 [ 0.93676627 -0.99999976  1.         -0.99602008 -0.98977089]
 [ 0.98058808 -1.          1.         -0.91650188 -0.99989784]]
